### ISSUE TITLE
Faire le HTML

### ISSUE THREAD

**Issue by piline** [Kozea/www-pharminfo#1]
- [x] one page : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbS1lzRGhiSzFUV3c/view?usp=sharing

- [x] page actualités : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbOUxyMHZBRFV1SlU/view?usp=sharing ( lien dans le menu, et les 4 derniers articles sont présents dans la première partie du site )

- [x]  page souscription des offres: https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbUTFvTEliay1nTEk/view?usp=sharing ( il s'agit du lien de pré-inscription qu'on trouve dans le tableau des offres )

- [x]  page téléchargement livre blanc : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbUXJIaFRMcjNEbWc/view?usp=sharing ( le lien est sur la home page )

- [x] popup de la vidéo de présentation de Pharminfo.fr dans la partie offre flexiweb plus

- [x] page de clients

- [x] page de mentions légales

**Comment by liZe** [comment]
La popup est à faire après en JS.
