### ISSUE TITLE
L'ajout d'une pop-up lors de l'arrivée sur le site est analysé

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-pharminfo#101]
Pour indiquer l'offre spéciale avec un bouton d'action contact
(brief à venir)

**Comment by Lilouu** [comment]
Face à l'actualité nous tenons à vous assurer que l'ensemble des équipes de Pharminfo.fr est mobilisée pour assurer la continuité de nos missions à votre service. Et pour vous soutenir dans cette épreuve, nous souhaitons vous accompagner davantage en vous proposant **un site internet* à 1€ / mois pendant 2 mois, sans engagement avec l'intégration de vos produits offerte.**

Bouton d'action : **Contactez-nous pour en savoir plus**
Avec redirection vers le mail contact@pharminfo.fr

_*Offre valable pour tout site internet Ecoweb, Flexiweb+ ou Click & Collect._

**Comment by annabellou** [comment]
Voici ma proposition : 

![Bandeau Pharminfo](https://user-images.githubusercontent.com/7512422/77157092-f5d65f00-6aa0-11ea-80d4-efa2dc6db4a7.png)

Après avoir fait le tour de plusieurs sites de vente en ligne, il en est ressorti que la tendance était plutôt au bandeau de texte qu’à une pop up.
Je propose donc un simple bandeau de texte, placé en bas de page, qui reste fixe même en scrollant la page. Il n’y a pas de possiblité de fermer / cacher ce bandeau. L’offre est mise en valeur ainsi que le bouton de contact.

Qu’en penses-tu @Lilouu ?

**Comment by gentooboontoo** [comment]
Perso j'aime bien, c'est plus simple à faire :wink:

**Comment by Lilouu** [comment]
ça me paraît bien, j'aime bien aussi, et tant mieux si c'est plus simple du coup ! 
Attention je crois qu'il y a un espace en trop après "Face" mais sinon on peut partir la dessus, je te fais des tickets @gentooboontoo pour la suite :)
