### ISSUE TITLE
Les prix sont supprimés du site

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-pharminfo#107]
Suite https://github.com/Kozea/kozea/issues/1937
Comme sur les images ci-dessous, il faut supprimer tous les tarifs visibles dans la partie "Offres" du site : 
![Capture d’écran de 2020-09-29 10-43-19](https://user-images.githubusercontent.com/17597956/94535728-311ccc00-0242-11eb-8efa-ba150d5c6394.png)
Les tarifs pour chaque offre
![Capture d’écran de 2020-09-29 10-53-40](https://user-images.githubusercontent.com/17597956/94535721-2feb9f00-0242-11eb-8d40-99a099082554.png)
Ainsi que les frais de mise en ligne, commission et mise à jour des stocks et des prix
"* 199 € HT de frais de mise en ligne.
** Commission de paiement 0,9 % du panier HT."
"[...]15€ HT/mois. Mise à jour des prix disponible uniquement en France métropolitaine."

@annabellou à voir si tu dois regarder le côté graphique pour les changements que ça induit et si c'est toi ou @gentooboontoo qui effectuera les changements sur le site.

**Comment by gentooboontoo** [comment]
Comme vu tous ensemble, @annabellou va regarder les modifications graphiques éventuelles puis les intégrer au site. Je prendrai le relais en cas de besoin.

**Comment by annabellou** [comment]
Normalement c'est bien parti en production !
