### ISSUE TITLE
Les actualités sont supprimées

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-pharminfo#114]
![Capture d’écran de 2021-11-18 15-22-35](https://user-images.githubusercontent.com/17597956/142433168-1aafdd98-3ecc-4330-857f-d0db28778809.png)
![Capture d’écran de 2021-11-18 15-22-47](https://user-images.githubusercontent.com/17597956/142433188-5ec58e4f-a5ce-4f83-9e1b-acf10f9bfa88.png)
Sur la page d'accueil, il y a le bouton "Voir toutes les actualités" qui redirige vers : https://www.pharminfo.fr/news alors que ce n'est plus alimenté. On peut donc supprimer ce bandeau et cette page.

**Comment by gentooboontoo** [comment]
Fait et mis en ligne.
