### ISSUE TITLE
Les corrections sont apportées sur les offres

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-pharminfo#115]
Pour les nouveaux clients, la solution de paiement sera en supplément de l'abonnement Optiweb. 
Il faut donc le mentionner sur notre site internet (sans mettre de prix).

**Comment by Lilouu** [comment]
Comme vu avec @AssiDir, au final pas besoin de modifier le contenu du site pour l'offre Optiweb et la partie sur Ingénico, étant donné que la solution de vente et paiement en ligne sera toujours intégrée et qu'il n'y a pas de mention de prix sur le site.

En revanche @gentooboontoo serait-il possible de modifier le point "Prise de RDV (prestataire externe)" par "Prise de rendez-vous" tout court au niveau des offres stp ? Depuis que nous avons développé notre propre solution, ce point n'avait pas été modifié. Je modifie et t'assigne donc le ticket pour ce petit point. Merci d'avance !

**Comment by gentooboontoo** [comment]
Fait.
