### ISSUE TITLE
Faire les animations js

### ISSUE THREAD

**Issue by piline** [Kozea/www-pharminfo#14]
il faut rendre le site un peu plus vivant et dynamique avec des animations css

**Comment by hugobernard** [comment]
- [ ] Header : faire apparaître le contenu de la même manière que sur le site de kozea.
- [ ] Blocs "articles", "garanties" et "personnalisez" : apparition en crescendo comme l'instagram de kozea
- [ ] Reasons : apparition "gauche droite gauche droite"
- [ ] Offres : apparition en décrescendo
