### ISSUE TITLE
Intégrer page d'accueil - mobile

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-pharminfo#15]
Intégrer les parties suivantes :

- [x] Navigation
- [x] Header
- [ ] About
- [x] News
- [x] Goals
- [x] Guarantees
- [x] Reasons
- [ ] Clients
- [x] Offers
- [x] Main offer
- [x] Customize
- [ ] Contact
- [x] Footer

**Comment by liZe** [comment]
Tu peux fermer le ticket quand ça te paraît bon !

**Comment by hugobernard** [comment]
Il reste à faire le style pour certaines parties qui nécessitent l'intervention d'un dev alors je pensais attendre d'avoir vraiment tout fini pour fermer le ticket...

**Comment by hugobernard** [comment]
Nouveau ticket >>
https://github.com/Kozea/www-pharminfo/issues/25
