### ISSUE TITLE
Rédiger explications pour la réservation d'ordo sur nouveau www

### ISSUE THREAD

**Issue by Maxouuu** [Kozea/www-pharminfo#32]
Pour le bloc "laissez-vous tenter par l'offre Flexiweb+"

**Comment by hugobernard** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/20473458/18243810/34a48db8-735d-11e6-969f-f79be3bfe191.png)

**Comment by hugobernard** [comment]
**4:** Le pharmacien prévient le patient par mail ou SMS quand l'ordonnance est prête

**Comment by Maxouuu** [comment]
https://docs.google.com/a/kozea.fr/document/d/1Pljq6I_BBK4bFOrcqJe40lPdvMiVIsxePn_aCFNhiAo/edit?usp=sharing
