### ISSUE TITLE
Changer le lien vers la vidéo de présentation (feedback pauline)

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-pharminfo#42]
lien "voir la video de présentation" devrait juste ouvrir le player et pas renvoyer vers la landing page (comme sur medsite.fr)

**Comment by Le-Stagiaire** [comment]
En fait en y réfléchissant c'est peut-être mieux d'aller sur la landing, parce qu'il y a des visuels de l'appli, une vraie présentation, en plus de la vidéo, qu'en penses-tu @hugobernard ?

**Comment by Le-Stagiaire** [comment]
Maxime a dit : 'pauline ses idées c'est d'la merde'
