### ISSUE TITLE
Vérifier les "1300" patients sondés pour les stats

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-pharminfo#50]

**Comment by Maxouuu** [comment]
En réalité environ 150 patients répondants.
(pour info, j'ai commencé à compter dès février 2016)

**Comment by hugobernard** [comment]
@clemenceprem est-ce qu'on laisse "1300" ou bien on change pour "150" ?

**Comment by Maxouuu** [comment]
On peut laisser 1300 car :
- c'est ce qu'il y a sur l'admin donc c'est "officiel" 
- on avait communiqué sur ce chiffre dans les infographies
