### ISSUE TITLE
La vidéo Click and collect est disponible sur le www

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-pharminfo#68]
@hugobernard mettre un bouton  " voir la vidéo Click and Collect" à côté de "découvrez l'application Pharminfo"

A mettre en ligne après le 10 juin. Merci

**Comment by hugobernard** [comment]
Je crois que c'est plus à @liZe de le faire ;)

**Comment by liZe** [comment]
@clemenceprem C'est quoi le lien de la vidéo Click and Collect ?

**Comment by clemenceprem** [comment]
https://youtu.be/fSRU--88LY4
