### ISSUE TITLE
Les images sont visibles sur la page actualité Pharminfo.fr

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-pharminfo#69]
Il faut augmenter la hauteur du bloc

**Comment by hugobernard** [comment]
Fixons donc une dimensions pour ces images, ainsi elles seront toujours bien intégrées et ce sera top !

**Comment by hugobernard** [comment]
Quelque chose comme 550x330 px ? 5/3 en proportion ça me semble pas mal !

**Comment by hugobernard** [comment]
En fait on va prendre 4/3 comme proportions comme ça on peut garder certaines images déjà faite en 770px par 578px (= 4/3)
