### ISSUE TITLE
Mettre en place le bouton click to call et les différents formulaires

### ISSUE THREAD

**Issue by piline** [Kozea/www-pharminfo#7]
https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbS1lzRGhiSzFUV3c/view?usp=sharing

**Comment by hugobernard** [comment]
**Suggestion : Cacher le bouton click to call** 
Quand on est en haut de page **ou** quand on scroll vers le haut, le faire apparaître.
Le cacher quand on scroll (vers le bas) pour ne pas gêner la lecture du contenu

**Comment by liZe** [comment]
Voir ce qui est fait dans BackOffice.
