### ISSUE TITLE
Les textes du site sont intégrés 

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-pharminfo#87]
https://docs.google.com/document/d/13eK6O61AEOQlLJw7mCY9qdGPgQyiQHnN3PD0VAq5204/edit?usp=sharing

**Comment by clemenceprem** [comment]
Délègue donc à @annabellou si tu n'as pas le temps...

**Comment by liZe** [comment]
@clemenceprem J'ai mis en ligne (dispo dans quelques minutes), tu me diras si ça te va !
